version: "3.2"
services:
    node-app:
        build: 
            context: .
            args: 
                - NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: npm start
        # command: node index.js