FROM node:12.18.1
WORKDIR /app
COPY package.json .

RUN if [ "$ENV NODE_ENV" = "production" ]; \
        then npm install; \
        else npm install --only=production;\
        fi

COPY . ./
ENV PORT 3000
EXPOSE $PORT
CMD [ "node", "index.js" ]