version: "3.2"
services:
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_INITDB_ROOT_USERNAME=rexie
            - MONGO_INITDB_ROOT_PASSWORD=123456
        command: npm run dev
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rexie
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes: 
            - mongo-db:/data/db 

volumes: 
    mongo-db: