version: "3.2"
services:
    node-app:
        build: .
# if both environment is the same then put both port here
# else put in various file i.e. dev and prod
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000

    mongo:
        image: mongo
        env_file: 
            - ./.env
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rexie
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes: 
           - mongo-db:/data/db 

volumes: 
    mongo-db: