version: "3.2"
services:
    node-app:
        build: 
            context: .
            # dockerfile: 
            args: 
        ports:
            - "3000:3000"
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - PORT=3000
        # env_file: 
        #     - ./.env
