version: "3.2"
services:
    nginx:
        image: nginx:stable-alpine
    node-app:
        build: .
# if both environment is the same then put both port here
# else put in various file i.e. dev and prod
        environment: 
            - PORT=3000
        depends_on: 
            - mongo

    mongo:
        image: mongo
        # env_file: 
        #     - ./.env
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rexie
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes: 
           - mongo-db:/data/db 

        
    redis:
        image: redis

volumes: 
    mongo-db: