version: "3.2"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:80"
    node-app:
        build: .
#   needed for production pull from github
        image: rexiemedia01/node-app
# if both environment is the same then put both port here
# else put in various file i.e. dev and prod
        environment: 
            - PORT=3000
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
        depends_on: 
            - mongo

    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes: 
           - mongo-db:/data/db 

        
    redis:
        image: redis

volumes: 
    mongo-db: